### ISSUE TITLE
Firebase setup for Realtime database

### ISSUE THREAD

**Issue by parw8649** [parw8649/CST438-Project2#23]
Replacing existing MySQL database connection with Firebase configuration for database

**Comment by bKondo** [comment]
I think we need 3 tables. Does this seem correct to you?

**users**
- string: name, UNIQUE --> primary key?
- string: pass
- boolean: admin

**items**
- int id, primary key, auto-increment?
- string link
- string description
- string image (url)

**lists**
- userId, foreign key: users id
- itemId, foreign key: items id

**Comment by parw8649** [comment]
Yes Barbara I think it looks good.
